matrix:
  include:
    - script:
        - set -o pipefail
        - xcodebuild $XCODE_ACTION -scheme "ReflectedStringConvertible OSX" | xcpretty
        - xcodebuild $XCODE_ACTION -scheme "ReflectedStringConvertible iOS" -sdk iphonesimulator -destination "name=iPhone SE" | xcpretty
      env:
        - JOB=Xcode
        - XCODE_ACTION="build-for-testing test-without-building"
      os: osx
      osx_image: xcode8.3
      language: objective-c
notifications:
  email: false